config/routes.rb
Rails.application.routes.draw do

  namespace :api, format: :json do
    resources :vacancies do
      get :search, on: :collection
    end
    resources :employees do
      get :search, on: :collection
    end
    resources :skills, only: :index
  end

  scope module: :web do
    resources :vacancies
    resources :employees
    resources :skills
    root 'index#index'
  end

end

app/models/skill.rb
class Skill < ActiveRecord::Base
  validates :name, uniqueness: true

  has_many :vacancy_skills
  has_many :vacancies, through: :vacancy_skills

  has_many :employee_skills
  has_many :employees, through: :employee_skills
end
# == Schema Information
#
# Table name: skills
#
#  id         :integer          not null, primary key
#  name       :string
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_skills_on_name  (name)
#

app/controllers/api/skills_controller.rb
class Api::SkillsController < Api::ApplicationController
  respond_to  :json

  def index
    @skills = Skill.all
    render json: @skills
  end
end

app/controllers/web/skills_controller.rb
class Web::SkillsController < Web::ApplicationController
  before_action :set_skill, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /skills
  def index
    @skills = Skill.all
    respond_with @skills
  end

  # GET /skills/1
  def show
  end

  # GET /skills/new
  def new
    @skill = Skill.new
  end

  # GET /skills/1/edit
  def edit
  end

  # POST /skills
  def create
    @skill = Skill.new(skill_params)
    if @skill.save
      redirect_to skills_path
    else
      render action: :new
    end
  end

  # PATCH/PUT /skills/1
  def update
    if @skill.update(skill_params)
      redirect_to skills_path
    else
      render action: :new
    end
  end

  # DELETE /skills/1
  def destroy
    @skill.destroy
    redirect_to skills_url
  end

  private
    def set_skill
      @skill = Skill.find(params[:id])
    end

    def skill_params
      params.require(:skill).permit(
        :name, :added_at, :expires_at, :salary, :contact_info,
        skills_attributes: [:id, :name, :_destroy]
      )
    end
end

app/views/web/skills/_form.html.slim
= simple_form_for(@skill) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
  .form-actions
    = f.button :submit

app/views/web/skills/edit.html.slim
h1 Editing skill

== render 'form'

br

= link_to 'Show', @skill
'|
= link_to 'Back', skills_path

app/views/web/skills/index.html.slim
div
  h1 Listing skills

  table.table.table-striped
    thead
      tr
        th id
        th Name
        th
        th
        th

    tbody
      - @skills.each do |skill|
        tr
          td = skill.id
          td = skill.name
          td = link_to "Show", skill_path(skill)
          td = link_to 'Edit', edit_skill_path(skill)
          td = link_to 'Destroy', skill, data: {:confirm => 'Are you sure?'}, :method => :delete

  br

  = link_to 'New Skill', new_skill_path

app/views/web/skills/new.html.slim
h1 New skill

== render 'form'

= link_to 'Back', skills_path

app/views/web/skills/show.html.slim
p#notice = notice

p
  strong Name:
  = @skill.name

= link_to 'Edit', edit_skill_path(@skill)
'|
= link_to 'Back', skills_path