config/routes.rb
Rails.application.routes.draw do

  namespace :api, format: :json do
    resources :vacancies do
      get :search, on: :collection
    end
    resources :employees do
      get :search, on: :collection
    end
    resources :skills, only: :index
  end

  scope module: :web do
    resources :vacancies
    resources :employees
    resources :skills
    root 'index#index'
  end

end

app/models/vacancy.rb
class Vacancy < ActiveRecord::Base
  has_many :vacancy_skills
  has_many :skills, through: :vacancy_skills

  accepts_nested_attributes_for :skills, :reject_if => :all_blank, :allow_destroy => true

  def self.search_by(employee)
    employee_skill_ids = employee.skill_ids
    if employee_skill_ids.any?
      vacancies = Vacancy.joins(:vacancy_skills).
        select("vacancies.id, vacancies.*, \
         array_agg(vacancy_skills.skill_id) @> ARRAY[#{employee_skill_ids.join(',')}] as full_matched,
         array_agg(vacancy_skills.skill_id) && ARRAY[#{employee_skill_ids.join(',')}] as matched" ).
        group('vacancies.id').
        order('full_matched desc, salary desc').
        where('expires_at >= ?', Date.today)
      matched, not_matched = vacancies.partition{|e| e.matched? }
      full_matched, partially_matched = matched.partition{|e| e.full_matched? }
    else
      full_matched, partially_matched = [], Vacancy.where('expires_at >= ?', Date.today).order(salary: :desc)
    end
  end

end

# == Schema Information
#
# Table name: vacancies
#
#  id           :integer          not null, primary key
#  name         :string
#  added_at     :date
#  expires_at   :date
#  salary       :integer
#  contact_info :text
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#

app/controllers/api/vacancies_controller.rb
class Api::VacanciesController < Api::ApplicationController
  before_action :set_vacancy, only: [:show, :edit, :update, :destroy]
  respond_to  :json

  def index
    @vacancies = Vacancy.all
    render json: @vacancies
  end

  def show
    render json: @vacancy
  end

  def new
    @vacancy = Vacancy.new
    render json: @vacancy
  end

  def edit
    render json: @vacancy
  end

  def create
    @vacancy = Vacancy.new(vacancy_params)
    @vacancy.save
    render json: @vacancy
  end

  def update
    if @vacancy.update(vacancy_params)
      skills = skills_set(skills_params)
      @vacancy.skills = skills
    end
    render json: @vacancy
  end

  def destroy
    @vacancy.destroy
    render json: @vacancy
  end

  def search
    employee = Employee.find(params[:employee_id])
    full_matched, partially_matched = Vacancy.search_by(employee)
    render json: { employee: employee,
                   full_matched: full_matched.as_json(each_serializer: VacancySerializer),
                   partially_matched: partially_matched.as_json(each_serializer: VacancySerializer) }
  end

  private
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    def vacancy_params
      params.require(:vacancy).permit(:name, :added_at, :expires_at, :salary, :contact_info)
    end

    def skills_params
      params.fetch(:skills, []) || []
    end

    def skills_set(skills)
      skills.map do |skill|
        Skill.find_or_initialize_by(name: skill[:name])
      end.uniq
    end
end

app/controllers/web/vacancies_controller.rb
class Web::VacanciesController < Web::ApplicationController
  before_action :set_vacancy, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /vacancies
  def index
    @vacancies = Vacancy.all
    respond_with @vacancies
  end

  # GET /vacancies/1
  def show
  end

  # GET /vacancies/new
  def new
    @vacancy = Vacancy.new
  end

  # GET /vacancies/1/edit
  def edit
  end

  # POST /vacancies
  def create
    @vacancy = Vacancy.new(vacancy_params)
    if @vacancy.save
      redirect_to vacancies_path
    else
      puts "*"*100
      @vacancy.errors.full_messages
      render action: :new
    end
  end

  # PATCH/PUT /vacancies/1
  def update
    if @vacancy.update(vacancy_params)
      redirect_to vacancies_path
    else
      render action: :new
    end
  end

  # DELETE /vacancies/1
  def destroy
    @vacancy.destroy
    redirect_to vacancies_url
  end

  private
    def set_vacancy
      @vacancy = Vacancy.find(params[:id])
    end

    def vacancy_params
      params.require(:vacancy).permit(
        :name, :added_at, :expires_at, :salary, :contact_info,
        skills_attributes: [:id, :name, :_destroy]
      )
    end
end

app/views/web/vacancies/_form.html.slim
= simple_form_for(@vacancy) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :added_at, as: :string, input_html: {  class: 'datepicker' }
    = f.input :expires_at, as: :string, input_html: {  class: 'datepicker' }
    = f.input :salary
    h4 Skills
    #tasks
      = f.simple_fields_for :skills do |skill|
        = render 'skill_fields', f: skill
      .links
        = link_to_add_association 'add skill', f, :skills

    = f.input :contact_info

  .form-actions
    = f.button :submit

app/views/web/vacancies/_skill_fields.html.slim
.nested-fields
  = f.input :name
  = link_to_remove_association "remove skill", f

app/views/web/vacancies/edit.html.slim
h1 Editing vacancy

== render 'form'

= link_to 'Show', @vacancy
'|
= link_to 'Back', vacancies_path

app/views/web/vacancies/index.html.slim
div
  h1 Listing vacancies

  table.table.table-striped
    thead
      tr
        th id
        th Name
        th Added at
        th Expires at
        th Salary
        th Contact info
        th
        th
        th

    tbody
      - @vacancies.each do |vacancy|
        tr
          td = vacancy.id
          td = vacancy.name
          td = vacancy.added_at
          td = vacancy.expires_at
          td = vacancy.salary
          td = vacancy.contact_info
          td = link_to "Show", vacancy_path(vacancy)
          td = link_to 'Edit', edit_vacancy_path(vacancy)
          td = link_to 'Destroy', vacancy, data: {:confirm => 'Are you sure?'}, :method => :delete

  br

  = link_to 'New Vacancy', new_vacancy_path

app/views/web/vacancies/new.html.slim
h1 New vacancy

== render 'form'

= link_to 'Back', vacancies_path

app/views/web/vacancies/show.html.slim
p#notice = notice

p
  strong Name:
  = @vacancy.name
p
  strong Added at:
  = @vacancy.added_at
p
  strong Expires at:
  = @vacancy.expires_at
p
  strong Salary:
  = @vacancy.salary
p
  strong Contact info:
  = @vacancy.contact_info

= link_to 'Edit', edit_vacancy_path(@vacancy)
'|
= link_to 'Back', vacancies_path