config/routes.rb
Rails.application.routes.draw do

  namespace :api, format: :json do
    resources :vacancies do
      get :search, on: :collection
    end
    resources :employees do
      get :search, on: :collection
    end
    resources :skills, only: :index
  end

  scope module: :web do
    resources :vacancies
    resources :employees
    resources :skills
    root 'index#index'
  end

end

app/models/employee.rb
class Employee < ActiveRecord::Base
  has_many :employee_skills
  has_many :skills, through: :employee_skills

  validate :name_validation, :contact_info_validation

  accepts_nested_attributes_for :skills, :reject_if => :all_blank, :allow_destroy => true

  def self.search_by(vacancy)
    vacancy_skill_ids = vacancy.skill_ids
    if vacancy_skill_ids.any?
      employees = Employee.joins(:employee_skills).
        select("employees.id, employees.*, \
         array_agg(employee_skills.skill_id) @> ARRAY[#{vacancy_skill_ids.join(',')}] as full_matched,
         array_agg(employee_skills.skill_id) && ARRAY[#{vacancy_skill_ids.join(',')}] as matched" ).
        group('employees.id').
        order('full_matched desc, salary').
        where(job_search_status: true)
      matched, not_matched = employees.partition{|e| e.matched? }
      full_matched, partially_matched = matched.partition{|e| e.full_matched? }
    else
      full_matched, partially_matched = [], Employee.where(job_search_status: true).order(:salary)
    end
    [full_matched, partially_matched]
  end

  def name_validation
    unless name_valid?
      errors[:name] << 'Неверный формат имени'
    end
  end

  def contact_info_validation
    if !(contact_include_email? || contact_include_phone_number?)
      errors[:contact_info] << 'Отсутствует контактная информация'
    end
  end

  def name_valid?
    name =~ /^([А-Яа-я]+\ ){2}[а-яА-Я]+$/
  end

  def contact_include_email?
    (contact_info =~ /.+@.+/).present?
  end

  def contact_include_phone_number?
    (contact_info =~ /\+[0-9]{11}/).present?
  end
end

# == Schema Information
#
# Table name: employees
#
#  id                :integer          not null, primary key
#  name              :string
#  contact_info      :text
#  job_search_status :boolean
#  salary            :integer
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#

app/controllers/api/employees_controller.rb
class Api::EmployeesController < Api::ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  respond_to  :json

  def index
    @employee = Employee.all
    render json: @employee
  end

  def show
    render json: @employee
  end

  def new
    @employee = Employee.new
    render json: @employee
  end

  def edit
    render json: @employee
  end

  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      render json: @employee, status: :created, location: @employee
    else
      render json: @employee.errors, status: :unprocessable_entity
    end
  end

  def update
    if @employee.update(employee_params)
      skills = skills_set(skills_params)
      @employee.skills = skills
      render json: @employee, status: :ok, location: @employee
    else
      render json: @employee.errors, status: :unprocessable_entity
    end
  end

  def destroy
    @employee.destroy
    render json: @employee
  end

  def search
    vacancy = Vacancy.find(params[:vacancy_id])
    full_matched, partially_matched = Employee.search_by(vacancy)
    render json: { vacancy: vacancy,
                   full_matched: full_matched.as_json(each_serializer: EmployeeSerializer),
                   partially_matched: partially_matched.as_json(each_serializer: EmployeeSerializer) }
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(:id, :name, :job_search_status, :salary, :contact_info)
    end

    def skills_params
      params.fetch(:skills, []) || [] # not production ready :(
    end

    def skills_set(skills)
      skills.map do |skill|
        Skill.find_or_initialize_by(name: skill[:name])
      end.uniq
    end
end

app/controllers/web/employees_controller.rb
class Web::EmployeesController < Web::ApplicationController
  before_action :set_employee, only: [:show, :edit, :update, :destroy]
  respond_to :html, :json

  # GET /employees
  def index
    @employees = Employee.all
    respond_with @employees
  end

  # GET /employees/1
  def show
  end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
  end

  # POST /employees
  def create
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employees_path
    else
      render action: :new
    end
  end

  # PATCH/PUT /employees/1
  def update
    if @employee.update(employee_params)
      redirect_to employees_path
    else
      render action: :new
    end
  end

  # DELETE /employees/1
  def destroy
    @employee.destroy
    redirect_to employees_url
  end

  private
    def set_employee
      @employee = Employee.find(params[:id])
    end

    def employee_params
      params.require(:employee).permit(
        :name, :job_search_status, :salary, :contact_info,
        skills_attributes: [:id, :name, :_destroy]
      )
    end
end

app/views/web/employees/_form.html.slim
= simple_form_for(@employee) do |f|
  = f.error_notification

  .form-inputs
    = f.input :name
    = f.input :job_search_status
    = f.input :salary
    h4 Skills
    #tasks
      = f.simple_fields_for :skills do |skill|
        = render 'skill_fields', f: skill
      .links
        = link_to_add_association 'add skill', f, :skills

    = f.input :contact_info

  .form-actions
    = f.button :submit

app/views/web/employees/_skill_fields.html.slim
.nested-fields
  = f.input :name
  = link_to_remove_association "remove skill", f

app/views/web/employees/edit.html.slim
h1 Editing employee

== render 'form'

= link_to 'Show', @employee
'|
= link_to 'Back', employees_path

app/views/web/employees/index.html.slim
div
  h1 Listing employees

  table.table.table-striped
    thead
      tr
        th id
        th Name
        th Search job
        th Salary
        th Contact info
        th
        th
        th

    tbody
      - @employees.each do |employee|
        tr
          td = employee.id
          td = employee.name
          td = employee.job_search_status
          td = employee.salary
          td = employee.contact_info
          td = link_to "Show", employee_path(employee)
          td = link_to 'Edit', edit_employee_path(employee)
          td = link_to 'Destroy', employee, data: {:confirm => 'Are you sure?'}, :method => :delete

  br

  = link_to 'New Employee', new_employee_path

app/views/web/employees/new.html.slim
h1 New employee

== render 'form'

= link_to 'Back', employees_path

app/views/web/employees/show.html.slim
p#notice = notice

p
  strong Name:
  = @employee.name
p
  strong Added at:
  = @employee.added_at
p
  strong Expires at:
  = @employee.expires_at
p
  strong Salary:
  = @employee.salary
p
  strong Contact info:
  = @employee.contact_info

= link_to 'Edit', edit_employee_path(@employee)
'|
= link_to 'Back', employees_path